# arg 1:  the new package version
post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

## arg 1:  the new package version
## arg 2:  the old package version
#pre_upgrade() {
#  pre_remove "$1"
#}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install "$2"
}

# arg 1:  the old package version
post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

# vim:set ts=2 sw=2 et:
